# mlflow-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: asia-east1-docker.pkg.dev/genibuilder/mlflow-gcp/mlflow-gcp@sha256:c41ba2830c193181a3d90e996a92371471f7f402cd2fb313b79963b8e3a74074
        ports:
        - containerPort: 5000
        env:
        - name: GCP_PROJECT
          value: "genibuilder"
        - name: PORT
          value: "5000"
        - name: HOST
          value: "0.0.0.0"