apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "wikipedia-agent"
  namespace: "mlflow-kserve"
spec:
  predictor:
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "gs://wiwi-bucket/1/15a6b7e29ad34d3fa1484ee9e0621774/artifacts/porygon_chain"
