apiVersion: v1
kind: Pod
metadata:
  name: curl-test-pod
  labels:
    app: curl-test
spec:
  containers:
  - name: curl-container
    image: ubuntu:22.04
    command: ["/bin/sh", "-c"]
    args:
    - |
      apt-get update && apt-get install -y curl && \
      echo "Curl installed. Pod will keep running..." && \
      tail -f /dev/null
  restartPolicy: Always